#!/bin/sh
name=$1

if [ -z "$TEX_TEMPLATE" ]; then
    echo "TEX_TEMPLATE unset!"
    exit 1
fi

if [ -z "$name" ]; then
    echo "No name supplied!"
    exit 1
fi

mkdir $name
cp -r $TEX_TEMPLATE/ $name/
cd $name
mv *.tex $name.tex
